import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/ThemeProvider/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    console.log("\n\n\n\n=======================\nNEW RENDER\n\n");
    return (
        <html lang='en'>
            <body className={inter.className}>
                <ThemeProvider attribute='data-theme'>{children}</ThemeProvider>
            </body>
        </html>
    );
}
